### ISSUE TITLE
blueprint

### ISSUE THREAD

**Issue by zetsumi** [rancoud/twitch#6]
* Pourquoi faire le projet BluePrint alors que tu ne fais pas de dev sur unreal engine ?
* Comment l'idee t elle venu ?
* Pourquoi tu ne veux pas faire de Go ?
* Quels etait ton sport preferer a l'ecole ?
* As-tu fait ton attestation pour sortir ?

**Comment by rancoud** [comment]
Réponses dans le commit https://github.com/rancoud/twitch/commit/0fb13854d68dd07d8f6791ab32f3fd08336d9c03
